### PR TITLE
[WIP] make log emits more closely adhere to Haraka logging format

### PR DESCRIPTION
**Pull request by KingNoosh**
### Original
**default:**
`[INFO] [98269ABB-CFBB-4A47-A107-C40D8272A470.1] [test] anosh: amazing, pass:true`
**logfmt:**
`level=INFO uuid=5C425B85-7FC9-4A3A-9722-6E81012D71D6.1 origin=test message="anosh: amazing, pass:true"`

### New
**default:**
`[INFO] [0633015A-8145-4CCA-8187-A93B8CC96D22.1] [test] pass=true fail="" msg="" err="" skip="" anosh=amazing human="anosh: amazing, pass:true" human_html="anosh: amazing,      pass:true"`
**logfmt:**
`level=INFO uuid=0F7096F8-EEBF-40E2-895E-936437524EC8.1 origin=test message="" pass=true,true fail="" msg="" err="" skip="" anosh=amazing human="anosh: amazing, pass:true" human_html="anosh: amazing,   pass:true"`

Checklist:
- [x] docs updated
- [x] tests updated
- [x] Changes.md updated
- [x] package.json.version bumped
- [ ] published to NPM (will be done by @core)

### CODE REVIEW

**Comment by KingNoosh** [comment]
Original
default: `[INFO] [98269ABB-CFBB-4A47-A107-C40D8272A470.1] [test] anosh: amazing, pass:true`
logfmt: `level=INFO uuid=5C425B85-7FC9-4A3A-9722-6E81012D71D6.1 origin=test message="anosh: amazing, pass:true"`

New
default: `[INFO] [0633015A-8145-4CCA-8187-A93B8CC96D22.1] [test] pass=true fail="" msg="" err="" skip="" anosh=amazing human="anosh: amazing, pass:true" human_html="anosh: amazing,      pass:true"`
logfmt: `level=INFO uuid=0F7096F8-EEBF-40E2-895E-936437524EC8.1 origin=test message="" pass=true,true fail="" msg="" err="" skip="" anosh=amazing human="anosh: amazing, pass:true" human_html="anosh: amazing,   pass:true"`

**Comment by smfreegard** [comment]
Should the human and human_html even be output to the logs?  e.g. it's just repeating what has already been displayed albeit in a different format.

**Comment by KingNoosh** [comment]
I'm not even 100% sure what `human` and `human_html` was being used for, afaik it's used in https://github.com/haraka/haraka-plugin-watch. I need to also respect the _hidden variables that are passed through and not log them, keeping the same functionality.

I'm going to need to do some more looking into how I'm going to go about this without breaking anything and without making it bulkier.

**Comment by msimerson** [comment]
> Should the human and human_html even be output to the logs

Nope. As @KingNoosh found, its used by the web UI.

**Comment by msimerson** [comment]
Stalled. Incomplete.

**Pull request closed without merging**
