### PR TITLE
add redis_publish config option

### PR DESCRIPTION
**Pull request by msimerson**

### CODE REVIEW

**Comment by smfreegard** [comment]
Uhm - where was the review for this?

Thanks for actually doing a patch, but this doesn't actually solve the broken default does it- it just allows for it to be switched off.

**Comment by msimerson** [comment]
Did you know that even with branch protection on master, if one happens to have the same commit in their local master branch as an open PR, that a push attempt (even an inadvertent one by a script or GitHub Desktop's "sync" button) will succeed and automatically close the PR?  Apparently its can and it surprised me.

You're right Steve, this PR does not change the working "on by default" behavior. But none of the implementations suggested or attempted thus far do so without user impact or edge cases. Thus I extended this olive branch because it's common ground. I was trying to be kind and avoid @baudehlo having to manage three children.

I think anything involving connection notes will always have edge cases, primarily due to plugin ordering. I suspect that a solution pleasing to everyone will involve a mutex such as `has_subscribers`. It could get switched on explicitly by plugins `needs_redis_publish()` or better still, it could get automatically enabled when any plugin subscribes to redis.

**Comment by baudehlo** [comment]
It doesn't solve the "broken default" but it's now been "broken" for long enough that @msimerson rightly points out that changing the default could break things in worse ways for enough people.

Thankfully the "broken default" is just a performance problem, and so this option allows those who care about performance to get that performance edge back, so I'm +1 on the change.

**Comment by smfreegard** [comment]
Ok - but having spent 10 minutes looking at my original patch and actually installing karma and testing it manually - it works just fine.

Turns out it was just the unit tests that were wrong and that plugins.server doesn't work because of a bug in `_make_custom_require` that means plugins-as-a-package don't work like regular plugins.  Fixing that was a one-liner in `plugins.js`.

There is no 'race' condition or 'edge cases' as @msimerson claims because connection.notes aren't being used, they're **server.notes** and they are initialised in the **`register()` hook**, which is run as the plugins are loaded and before we even start listening, they're also not async, so it's **impossible** to race here.

We're relying on Redis more and more and this default really sucks for people that don't use the watch or karma plugins but either use the stock Redis plugin or just store the Redis connection in server.notes.redis.

I'm planning on adding Redis stuff into outbound eventually and this with make that much more likely to be painful for everyone.   Do we really want the docs to have to say `if you're not using the karma or watch plugin, make sure you set redis_publish=false in results.ini` or have to add this to the performance tips page on the Wiki?

I just wanted to get this fixed properly so that it *just works* for everyone concerned, with no surprises or performance penalties.

**Comment by msimerson** [comment]
I believe it's safe to say we agree it's preferable to avoid publishing to redis unless there's something listening. Therefore, the only matter left to resolve is implementation.

I think changing every plugin that subscribes to redis pub/sub to also need to toggle a server note is a lousy solution.

The redis plugin has subscribe functions that are called by the plugins as their entry point. If our redis plugin did the work of setting a mutex aptly named like `has_subscribers`, then plugins don't need to be altered and everything should just work. That's an implementation that I think everyone would support.

**Comment by smfreegard** [comment]
> I believe it's safe to say we agree it's preferable to avoid publishing to redis unless there's something listening. Therefore, the only matter left to resolve is implementation.

Yes - I agree completely.

> I think changing every plugin that subscribes to redis pub/sub to also need to toggle a server note is a lousy solution.

You mean two plugins?  And an entry in the release notes just in case someone else is relying on this?

> The redis plugin has subscribe functions that are called by the plugins as their entry point. If our redis plugin did the work of setting a mutex aptly named like has_subscribers, then plugins don't need to be altered and everything should just work. That's an implementation that I think everyone would support.

Sure - I would support that.

But it needs to work for people like me that don't use the stock Redis plugin but still use `server.notes.redis` to hold the redis connection.

That would mean that haraka-results would have to default not to publish anything (making this commit redundant because the configuration setting would be unnessary) unless `haraka-plugin-redis` sets a specific server note, which is basically what I was already suggesting except this is going to have to happen at run-time instead of start-up which is going to have more potential for races than what I was suggesting.

**Pull request merged**
